# Usa a imagem oficial do MySQL
FROM mysql:8.4

# Copia o diretório de inicialização para dentro do contêiner
COPY mysql-init/init.sql /docker-entrypoint-initdb.d/

# Expondo a porta 3306 do MySQL
EXPOSE 3306